### ISSUE TITLE
Support for Brave

### ISSUE THREAD

**Issue by s0902rx** [Garulf/Browser-History#3]
Would be nice if the plugin supported the Brave browser.

**Comment by arthackrc** [comment]
vote up for this suggestion

**Comment by Garulf** [comment]
I'll take a look into adding support when I can. Shouldn't be too bad considering it's based on Chromium.

**Comment by arthackrc** [comment]
It's my first time suggesting a conclusion 
Maybe we only need to put this path in browser.py
C:\Users\xxxxx\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default\History

**Comment by Garulf** [comment]
Added in https://github.com/Garulf/Browser-History/pull/8 by @Spheres-cu
